FROM maifhorizon-docker-docker.bintray.io/parnassemaif/applicatif/keycloak:1.2.0
ENV item envvars[item]
ENV item envvars[item]
ENV item envvars[item]
ENV item envvars[item]
ENV item envvars[item]
ENV item envvars[item]
ENV item envvars[item]
ENV item envvars[item]
ENV item envvars[item]
ENV item envvars[item]
ENV item envvars[item]
ENV item envvars[item]
